import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { QueryClient, dehydrate } from '@tanstack/react-query';
import './globals.css';
import Providers from './providers';
import { fetchUserStatus } from '@features/auth/api';

const pretendard = localFont({
  src: [
    {
      path: '../public/fonts/Pretendard-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Pretendard-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: ['userStatus'],
    queryFn: fetchUserStatus,
  });

  const dehydratedState = dehydrate(queryClient);
  return (
    <html lang="en">
      <body className={pretendard.variable}>
        <Providers dehydratedState={dehydratedState}>{children}</Providers>
      </body>
    </html>
  );
}
